silhouette score
bumble-tech/buzzwords pull request #7
Opened 2022-12-19 08:21 UTC by lewisExternal

Hey @Steeeephen 

Following up on the recent Data Science Festival event, thanks again for the talk. 
As mentioned, adding an example of silhouette score as an intrinsic validator for clustering techniques. 
I did have to update one of the packages but I also had to change the rapids version to account for different hardware, so please validate the environment resolves before merging. 

Just a thought! 

REF 
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.silhouette_score.html
https://towardsdatascience.com/silhouette-coefficient-validating-clustering-techniques-e976bb81d10c

2022-12-20 00:30 UTC, Steeeephen requested changes
Really nice change, I like it. One small request outside of the comment - make it optional to print the output, not every end user may want to add it to their logs

2022-12-20 00:30 UTC, Steeeephen commented on buzzwords/buzzwords.py
> +    def get_silhouette_score(self, X: np.ndarray, labels: np.ndarray) -> float:
says it returns `float` but it actually returns `NoneType` from the print

think it's more intuitive to keep this as `-> float` and change the `print` to a `return`, then printing after calling it

2022-12-20 08:05 UTC, lewisExternal commented
Thanks @Steeeephen, all good points - these should now be resolved. 
Anything else, please do let me know.

2022-12-20 10:58 UTC, Steeeephen approved these changes
This is perfect, I really like it. Thanks so much for contributing! 🥺

2022-12-20 10:59 UTC, merged

2022-12-21 07:54 UTC, lewisExternal commented
> This is perfect, I really like it. Thanks so much for contributing! 🥺

Thanks for putting code into the wild and for the event, pizza for PRs seems like a fair exchange to me.

![1843_20210415_HAWAIIANPIZZA_001](https://user-images.githubusercontent.com/81447748/208850552-28114eb4-7cc6-4e21-92e4-811679970d76.jpg)